### ISSUE TITLE
The method driver /usr/lib/apt/methods/https could not be found.

### ISSUE THREAD

**Issue by akhchan** [CollinEstes/docker-node-oracle#13]
I'm trying out this project and got this error while docker build, error at step 2

Step 2/10 : RUN apt-get update   && apt-get install -y libaio1   && apt-get install -y build-essential   && apt-get inst
all -y unzip   && apt-get install -y curl
 ---> Running in 6c10db86ea99
E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c apt-get update   && apt-get install -y libaio1   && apt-get install -y build-essential   && apt-
get install -y unzip   && apt-get install -y curl' returned a non-zero code: 100

**Comment by CollinEstes** [comment]
Have never seen this one, but I haven't kept up, closing for now can reopen if still interested.
