### ISSUE TITLE
Tag 8 is not on dockerhub

### ISSUE THREAD

**Issue by eduardo-matos** [CollinEstes/docker-node-oracle#19]
I am getting this error when I try to pull the image on this tag.

![image](https://user-images.githubusercontent.com/483681/36984706-43dbba5c-2074-11e8-9a3c-46f7d133cb88.png)

**Comment by jpollard-cs** [comment]
+1

**Comment by CollinEstes** [comment]
deployed it

**Comment by jpollard-cs** [comment]
thanks!!
