### ISSUE TITLE
Error while pulling 

### ISSUE THREAD

**Issue by AlaRuba** [CollinEstes/docker-node-oracle#3]
Hi,

I'm using your Dockerfile to pull the oracleDB files in.
I was wondering if you had any idea what this error meant?

    /usr/src/app/node_modules/oracledb/build/Release/oracledb.node: invalid ELF header

It seems to have a problem with the files.

I am using node-oracledb

**Comment by CollinEstes** [comment]
I hit this error before when I installed node-oracledb in my dev environment (OSX) and added a COPY command of my source into my docker container which is a different environment.  The npm install of node-oracledb has some specific OS installations with the oracle instant client binaries.  (total assumption based on behavior I haven't poured through the code enough)

Are you installing node-oracledb in a diffent env from your docker container?

**Comment by CollinEstes** [comment]
You can either do the NPM install in your docker container (this is my preference), or you can run 'npm rebuild' in your Dockerfile.

**Comment by AlaRuba** [comment]
Ya I dev in an OSX enviroment, but the docker container runs unix. I've gotten node-oracledb to work in the OSX environment, however I'm trying to spin up an entire docker cluster that's going to run linux.

It's in the docker container where I get the ELF header. I'm pretty sure just trying to use your image for it.

On a side note, there are no problems in any environment with strong-oracle, which is pretty interesting.
