### ISSUE TITLE
TNS issues exist only inside the container

### ISSUE THREAD

**Issue by mikaturunen** [CollinEstes/docker-node-oracle#5]
Environment: OSX

## Running outside container

- Manually installed instantclient + sdk
- Python 2.7.x
- GCC
- npm installed oracledb 

Everything works like a wonder.

## Running inside the container

- `docker run -d --name rester -v ~/repos/rester/:/rester -w /rester -p 3000:3000 collinestes/docker-node-oracle:4.4.0``

Essentially saying run a container in the background, mounting a local directory to the `/rester` dir inside the container and exposing the port 3000 to local environment. Nothing major, just plain and simple.

When I run the application inside the container, `npm install` and everything finish just fine and dandy but the issues comes when it tries to getConnection from oracledb and I get the following message from the container:

**Error: ORA-12154: TNS:could not resolve the connect identifier specified**

Any tips on how to progress with this? As I know it works perfectly well on my local setup and just bonkers with the container. All tips are more than welcome.

EDIT 1:

```javascript
// getConnection options

{
    user: "unicorn_secret_user",
    password : "even_more_unicorn_password",
    connectString: "my_secret_ip_that_is_full_of_magic_and_wonders:1600/UNICORN"
}
```

**Comment by CollinEstes** [comment]
I'm know you have probably moved on from this, but I just got my applications working with this style of TNS connection.  

Could you still use some help?

**Comment by mikaturunen** [comment]
Aww, shucks, sorry man. I'm on vacation currently so cannot reproduce the issue as of now but let me get back to you in a month or so :) I know, I know... :)

We'll see at that point if this is still an issue or not and I'll throw in the complete code example and all.

**Comment by sibelius** [comment]
@mikaturunen how did u solve that? I have the same issue here

**Comment by sibelius** [comment]
my problem was that `host` was wrong
