### ISSUE TITLE
Node version 6 is not branched properly

### ISSUE THREAD

**Issue by dlabey** [CollinEstes/docker-node-oracle#9]
When trying to pull collinestes/docker-node-oracle:6 it does not exist. Using latest would possibly break a container build because the version is not locked in.

**Comment by dlabey** [comment]
Please get this merged in first https://github.com/CollinEstes/docker-node-oracle/pull/10

**Comment by CollinEstes** [comment]
Ok I got the 6 branch created properly and built in the docker-hub.

@dlabey as a side-note I also created the "wheezy-6.2.0" branch as well.  This is built off the Nodesource Debian images and are much smaller in total size than the base Node.js images.  

I think the base Node version is around ~900MB and the, Debian version is closer to 600MB.  

We use the Debian version for our APIs at NASA.

**Comment by dlabey** [comment]
Awesome thanks! 👍
